name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # Add multiple commands to run if needed
            bazelisk build //...
            bazelisk test //...